### ISSUE TITLE
Regions are Hardcoded and that makes me sad

### ISSUE THREAD

**Issue by cabbruzzese** [YashdalfTheGray/ecs-tester#4]
#### Type of issue
✨Feature Request

#### Urgency
⏰Normal

*If this is a feature request*
#### Describe feature
Need to provide ability to override or specify regions as configuration where they are hardcoded.

#### Expected behavior
Can specify regions without assumptions on region id

#### Actual behavior
Regions are hard coded and cannot be overridden.

**Comment by YashdalfTheGray** [comment]
Fixed in a20522d4b68a25a6b7e9e82a8fe8caa770d27285, added a `USE_FARGATE` flag to the .env file to completely remove the region AWS Fargate flag.

**Comment by YashdalfTheGray** [comment]
I also made the API access keys optional in 05718bd4db34777a0d6956e85d2f903bac2a67cb. The resources won't be deleted though.
