### ISSUE TITLE
Change Default naming of ECS Objects to include "-ecs-tester" to avoid naming conflicts

### ISSUE THREAD

**Issue by cabbruzzese** [YashdalfTheGray/ecs-tester#5]
#### Type of issue
✨Feature Request

#### Urgency
⏰Normal

#### Describe feature
Users who already have default named ECS objects will cause tests to fail. (I.e. a default cluster). Tests should append "-ecs-tester" to names to ensure they can be made without collision, and they can be cleaned up without accidentally deleting important resources.

#### Expected behavior
New object in test should be created with a name unique to the test to avoid collision. (I.e. default cluster in first run)

#### Actual behavior
Creates with default name and collides with existing resource

**Comment by YashdalfTheGray** [comment]
Solved in 5d479217431951df665187926fe8550d7f84be1a
