### ISSUE TITLE
Boolean process.env not checking for string 'true' | 'false'

### ISSUE THREAD

**Issue by cabbruzzese** [YashdalfTheGray/ecs-tester#6]
#### Type of issue
🐛Bug Report

#### Urgency
🚑Urgent

#### Reproduction steps
Create .env with USE_FARGATE=false
run tests

#### Expected behavior
Should treat value as fault and exclude FARGATE tests

#### Actual behavior
Treats as true because USE_FARGATE is string 'false' which evaluates to true

Example:
https://github.com/YashdalfTheGray/ecs-tester/blob/a20522d4b68a25a6b7e9e82a8fe8caa770d27285/src/ec2-firstrun.spec.js#L28

**Comment by YashdalfTheGray** [comment]
Fixed in 8c08b657bfdfcba78d17a2199c6f53a9c9f3a79e

Ended up going back to a function called `isFargateRegion` which looks at the environment variable `USE_FARGATE` to determine if the fargate tests should be enabled or not.
