### ISSUE TITLE
hacker.verb() users invalid character (space)

### ISSUE THREAD

**Issue by cabbruzzese** [YashdalfTheGray/ecs-tester#7]
#### Type of issue
🐛Bug Report

#### Urgency
🚑Urgent

#### Reproduction steps
Run tests until receiving a cluster name or repository name with a space

#### Expected behavior
Should never use invalid characters (such as spaces)

#### Actual behavior
Occasionally randomizer returns a space

![ecs-test-space](https://user-images.githubusercontent.com/697370/39329185-6c9450ec-4952-11e8-877a-f470587f760f.png)

**Comment by YashdalfTheGray** [comment]
Fixed in ac9af409a41c113b0f35e3bca3cbec17eb16dee2
